# Generated by Django 5.1.5 on 2025-02-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='otp',
            field=models.CharField(default='1111', max_length=6),
        ),
    ]
