# Generated by Django 5.1.5 on 2025-02-05 05:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_artist_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('art_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_img', models.ImageField(upload_to='posts/')),
                ('post_tag', models.CharField(max_length=255)),
                ('post_title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blogs.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
