# Generated by Django 5.1.5 on 2025-02-06 05:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('art_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_img', models.ImageField(upload_to='photographies/')),
                ('photo_tag', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographies', to='blogs.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
