# Generated by Django 5.1.5 on 2025-02-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_artistprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistprofile',
            old_name='twiiter',
            new_name='twitter',
        ),
    ]
