# Generated by Django 5.1.5 on 2025-02-17 05:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_rename_twiiter_artistprofile_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='postComment',
            fields=[
                ('art_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_text', models.TextField()),
                ('comment_user', models.CharField(max_length=255)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
